In [6]:
import pandas as pd

In [7]:
pip install pd

Requirement already satisfied: pd in /Users/fabiansegurondo/opt/anaconda3/lib/python3.9/site-packages (0.0.4)
Note: you may need to restart the kernel to use updated packages.

In [16]:
nbaPlayersStats = pd.read_excel(r"/Users/fabiansegurondo/UPB VII/AI/WebScraping_nbaStats/allPlayersStatsExample.xlsx" )

In [17]:
nbaPlayersStats

,Unnamed: 0,PLAYER,TEAM,AGE,GP,W,L,MIN,OFFRTG,DEFRTG,...,OREB%,DREB%,REB%,TOÂ Ratio,eFG%,TS%,USG%,PACE,PIE,POSS
0,0,Deni Avdija,WAS,21,82,35,47,24.2,109.2,110.1,...,2.7,18.2,10.6,9.7,50.3,53.6,15.8,99.88,8.6,"4,118"
1,1,Saddiq Bey,DET,23,82,23,59,33.0,104.7,114.0,...,3.5,12.5,7.8,6.1,48.9,52.9,20.9,99.32,10.0,"5,605"
2,2,Alec Burks,NYK,30,81,37,44,28.6,110.3,108.1,...,1.9,14.8,8.2,7.8,49.9,55.9,17.1,96.97,9.9,"4,691"
3,3,Buddy Hield,IND,29,81,26,55,30.8,111.4,115.1,...,2.5,11.4,6.8,10.1,52.6,54.8,21.4,100.47,8.4,"5,242"
4,4,Dwight Powell,DAL,30,81,51,30,21.9,112.9,110.7,...,9.8,13.4,11.6,9.7,68.5,72.6,13.5,95.03,10.3,"3,503"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,600,Sam Dekker,TOR,27,1,1,0,0.9,0.0,250.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.88,0.0,2
601,601,Scotty Hopson,OKC,32,1,0,1,17.7,81.6,100.0,...,0.0,4.3,2.4,28.6,50.0,50.0,14.3,101.50,1.8,38
602,602,Trayvon Palmer,DET,27,1,0,1,16.8,78.8,111.8,...,0.0,13.3,6.5,50.0,0.0,0.0,5.3,95.87,-3.7,33
603,603,Tyler Hall,NYK,25,1,1,0,1.9,40.0,140.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,124.14,0.0,5
604,604,Zylan Cheatham,UTA,26,1,0,1,5.2,18.2,125.0,...,0.0,0.0,0.0,0.0,0.0,0.0,25.0,106.50,-16.7,11

In [18]:
nbaPlayersStats.head()

,Unnamed: 0,PLAYER,TEAM,AGE,GP,W,L,MIN,OFFRTG,DEFRTG,...,OREB%,DREB%,REB%,TOÂ Ratio,eFG%,TS%,USG%,PACE,PIE,POSS
0,0,Deni Avdija,WAS,21,82,35,47,24.2,109.2,110.1,...,2.7,18.2,10.6,9.7,50.3,53.6,15.8,99.88,8.6,"4,118"
1,1,Saddiq Bey,DET,23,82,23,59,33.0,104.7,114.0,...,3.5,12.5,7.8,6.1,48.9,52.9,20.9,99.32,10.0,"5,605"
2,2,Alec Burks,NYK,30,81,37,44,28.6,110.3,108.1,...,1.9,14.8,8.2,7.8,49.9,55.9,17.1,96.97,9.9,"4,691"
3,3,Buddy Hield,IND,29,81,26,55,30.8,111.4,115.1,...,2.5,11.4,6.8,10.1,52.6,54.8,21.4,100.47,8.4,"5,242"
4,4,Dwight Powell,DAL,30,81,51,30,21.9,112.9,110.7,...,9.8,13.4,11.6,9.7,68.5,72.6,13.5,95.03,10.3,"3,503"

In [19]:
nbaPlayersStats.tail(15)

,Unnamed: 0,PLAYER,TEAM,AGE,GP,W,L,MIN,OFFRTG,DEFRTG,...,OREB%,DREB%,REB%,TOÂ Ratio,eFG%,TS%,USG%,PACE,PIE,POSS
590,590,DeJon Jarreau,IND,24,1,0,1,0.9,200.0,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,111.41,0.0,2
591,591,Jaime Echenique,WAS,24,1,1,0,3.1,20.0,50.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.43,0.0,5
592,592,Javin DeLaurier,MIL,24,1,1,0,2.8,171.4,114.3,...,0.0,25.0,20.0,0.0,0.0,0.0,0.0,120.00,5.1,7
593,593,Jaysean Paige,DET,27,1,1,0,6.6,43.8,113.3,...,0.0,9.1,4.3,20.0,0.0,0.0,21.1,112.44,-28.6,16
594,594,Joe Johnson,BOS,40,1,1,0,2.0,80.0,180.0,...,0.0,0.0,0.0,0.0,100.0,100.0,20.0,123.08,18.2,5
595,595,Jordan Bell,CHI,27,1,1,0,2.0,200.0,175.0,...,50.0,0.0,50.0,0.0,0.0,0.0,0.0,95.21,-3.3,4
596,596,Mac McClung,LAL,23,1,1,0,2.6,100.0,114.3,...,0.0,0.0,0.0,50.0,100.0,100.0,33.3,122.35,11.1,6
597,597,Malik Newman,CLE,25,1,0,1,7.7,91.7,83.3,...,0.0,10.0,5.3,12.5,60.0,68.0,43.8,74.97,51.9,12
598,598,Matt Mooney,NYK,27,1,1,0,1.9,40.0,140.0,...,0.0,0.0,0.0,50.0,0.0,0.0,40.0,124.14,-9.1,5
599,599,Matt Ryan,BOS,24,1,1,0,5.3,116.7,91.7,...,0.0,0.0,0.0,0.0,30.0,30.0,35.7,109.71,0.0,12
600,600,Sam Dekker,TOR,27,1,1,0,0.9,0.0,250.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.88,0.0,2
601,601,Scotty Hopson,OKC,32,1,0,1,17.7,81.6,100.0,...,0.0,4.3,2.4,28.6,50.0,50.0,14.3,101.50,1.8,38
602,602,Trayvon Palmer,DET,27,1,0,1,16.8,78.8,111.8,...,0.0,13.3,6.5,50.0,0.0,0.0,5.3,95.87,-3.7,33
603,603,Tyler Hall,NYK,25,1,1,0,1.9,40.0,140.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,124.14,0.0,5
604,604,Zylan Cheatham,UTA,26,1,0,1,5.2,18.2,125.0,...,0.0,0.0,0.0,0.0,0.0,0.0,25.0,106.50,-16.7,11

In [20]:
#describe, stat summary

nbaPlayersStats.describe()

,Unnamed: 0,AGE,GP,W,L,MIN,OFFRTG,DEFRTG,NETRTG,AST%,...,ASTÂ Ratio,OREB%,DREB%,REB%,TOÂ Ratio,eFG%,TS%,USG%,PACE,PIE
count,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,...,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000,605.000000
mean,302.000000,25.965289,42.798347,21.565289,21.233058,18.833223,105.809752,109.787769,-3.976860,13.350248,...,16.591240,4.473719,13.022975,8.751074,10.003636,49.448099,52.350579,17.601983,101.252793,8.204628
std,174.792734,4.126772,25.744844,15.361465,14.105453,9.801982,15.398445,12.124489,21.228781,9.949947,...,9.045503,4.263334,6.080888,4.755153,5.992091,14.907141,14.721673,6.105930,5.081186,5.713648
min,0.000000,19.000000,1.000000,0.000000,0.000000,0.800000,0.000000,40.500000,-250.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,70.430000,-28.600000
25%,151.000000,23.000000,17.000000,8.000000,8.000000,10.900000,103.600000,106.400000,-7.800000,6.900000,...,11.100000,1.700000,9.400000,5.700000,7.500000,46.700000,50.000000,13.800000,99.120000,6.400000
50%,302.000000,25.000000,48.000000,20.000000,22.000000,18.000000,108.300000,109.800000,-1.300000,10.600000,...,15.200000,3.100000,11.800000,7.600000,9.500000,51.900000,54.900000,16.900000,100.660000,8.300000
75%,453.000000,29.000000,66.000000,35.000000,31.000000,27.200000,112.000000,113.000000,3.500000,17.800000,...,21.300000,6.100000,16.400000,11.300000,11.800000,56.300000,59.300000,20.700000,102.290000,10.600000
max,604.000000,41.000000,82.000000,64.000000,59.000000,42.900000,200.000000,250.000000,133.300000,100.000000,...,50.000000,50.000000,38.900000,50.000000,50.000000,100.000000,100.000000,50.000000,142.290000,51.900000

In [21]:
nbaPlayersStats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  605 non-null    int64
 1   PLAYER      605 non-null    object
 2   TEAM        605 non-null    object
 3   AGE         605 non-null    int64
 4   GP          605 non-null    int64
 5   W           605 non-null    int64
 6   L           605 non-null    int64
 7   MIN         605 non-null    float64
 8   OFFRTG      605 non-null    float64
 9   DEFRTG      605 non-null    float64
 10  NETRTG      605 non-null    float64
 11  AST%        605 non-null    float64
 12  AST/TO      605 non-null    float64
 13  ASTÂ Ratio   605 non-null    float64
 14  OREB%       605 non-null    float64
 15  DREB%       605 non-null    float64
 16  REB%        605 non-null    float64
 17  TOÂ Ratio    605 non-null    float64
 18  eFG%        605 non-null    float64
 19  TS%         605 non-null    float64
 20  USG%        605 non-null    float64
 21  PACE        605 non-null    float64
 22  PIE         605 non-null    float64
 23  POSS        605 non-null    object
dtypes: float64(16), int64(5), object(3)
memory usage: 113.6+ KB

In [22]:
#look stats for my lukita

DoncicDataFrame = nbaPlayersStats[nbaPlayersStats['PLAYER'] == 'Luka Doncic']

In [23]:
DoncicDataFrame

,Unnamed: 0,PLAYER,TEAM,AGE,GP,W,L,MIN,OFFRTG,DEFRTG,...,OREB%,DREB%,REB%,TOÂ Ratio,eFG%,TS%,USG%,PACE,PIE,POSS
177,177,Luka Doncic,DAL,23,64,43,21,35.5,113.5,110.4,...,2.4,23.0,12.9,11.8,52.9,57.0,36.8,96.12,19.1,"4,543"

In [25]:
DoncicDataFrame.describe()

,Unnamed: 0,AGE,GP,W,L,MIN,OFFRTG,DEFRTG,NETRTG,AST%,...,ASTÂ Ratio,OREB%,DREB%,REB%,TOÂ Ratio,eFG%,TS%,USG%,PACE,PIE
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.00,1.0
mean,177.0,23.0,64.0,43.0,21.0,35.5,113.5,110.4,3.1,45.9,...,22.9,2.4,23.0,12.9,11.8,52.9,57.0,36.8,96.12,19.1
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,177.0,23.0,64.0,43.0,21.0,35.5,113.5,110.4,3.1,45.9,...,22.9,2.4,23.0,12.9,11.8,52.9,57.0,36.8,96.12,19.1
25%,177.0,23.0,64.0,43.0,21.0,35.5,113.5,110.4,3.1,45.9,...,22.9,2.4,23.0,12.9,11.8,52.9,57.0,36.8,96.12,19.1
50%,177.0,23.0,64.0,43.0,21.0,35.5,113.5,110.4,3.1,45.9,...,22.9,2.4,23.0,12.9,11.8,52.9,57.0,36.8,96.12,19.1
75%,177.0,23.0,64.0,43.0,21.0,35.5,113.5,110.4,3.1,45.9,...,22.9,2.4,23.0,12.9,11.8,52.9,57.0,36.8,96.12,19.1
max,177.0,23.0,64.0,43.0,21.0,35.5,113.5,110.4,3.1,45.9,...,22.9,2.4,23.0,12.9,11.8,52.9,57.0,36.8,96.12,19.1

In [28]:
#more than 40 wins And more than 35 min played
winOver40DataFrame = nbaPlayersStats[(nbaPlayersStats['W'] >= 40) & (nbaPlayersStats['MIN'] >= 35) ]

In [29]:
winOver40DataFrame

,Unnamed: 0,PLAYER,TEAM,AGE,GP,W,L,MIN,OFFRTG,DEFRTG,...,OREB%,DREB%,REB%,TOÂ Ratio,eFG%,TS%,USG%,PACE,PIE,POSS
6,6,Mikal Bridges,PHX,25,81,64,17,35.2,116.9,106.9,...,2.7,8.9,6.0,5.7,60.2,62.8,14.9,100.57,9.2,"5,963"
10,10,Miles Bridges,CHA,24,80,41,39,35.5,114.5,112.4,...,3.0,15.8,9.4,8.3,55.4,59.3,22.4,100.98,12.0,"5,975"
31,31,DeMar DeRozan,CHI,32,76,43,33,36.1,113.1,112.0,...,2.1,12.2,7.2,7.8,52.1,59.0,30.8,100.04,14.8,"5,723"
36,36,Jayson Tatum,BOS,24,76,49,27,35.9,115.5,103.4,...,3.2,18.0,10.9,9.4,52.6,57.8,31.3,98.12,15.9,"5,578"
50,50,Tyrese Maxey,PHI,21,75,45,30,35.3,113.3,109.7,...,1.0,8.0,4.6,5.9,55.2,59.4,19.9,97.10,10.5,"5,362"
62,62,Scottie Barnes,TOR,20,74,43,31,35.4,110.2,108.4,...,6.8,14.1,10.2,9.6,52.4,55.2,18.7,97.03,10.9,"5,277"
99,99,Gary Trent Jr.,TOR,23,70,44,26,35.0,113.5,110.2,...,1.0,7.0,3.8,5.3,51.1,54.6,21.2,97.94,8.6,"4,997"
125,125,Pascal Siakam,TOR,28,68,40,28,37.9,114.3,109.6,...,4.6,18.2,11.1,9.5,52.5,56.5,25.7,96.31,13.9,"5,177"
164,164,James Harden,PHI,32,65,40,25,37.2,114.9,111.4,...,2.4,17.6,10.3,13.1,48.5,58.3,26.6,99.49,15.3,"5,015"
177,177,Luka Doncic,DAL,23,64,43,21,35.5,113.5,110.4,...,2.4,23.0,12.9,11.8,52.9,57.0,36.8,96.12,19.1,"4,543"